### ISSUE TITLE
BUG : v3.14.0 throwing constant `globalThis.addEventListener is not a function` errors

### ISSUE THREAD

**Issue by riceboyler** [rudderlabs/rudder-sdk-js#2040]
**Describe the bug**
Since moving to v3.14.0 of @rudderstack/analytics-js, when running a local dev environment for Next.js, the console is filled with `TypeError: globalThis.addEventListener is not a function` errors pointing to the Rudderstack library.

**To Reproduce**

1. Create a new NextJS application `npx create-next-app`
2. Initialize Rudderstack in `layout.tsx`
3. Add a useEffect to `page.tsx` calling `rudderAnalytics.page` (make sure you add `use client` at the top of the page.tsx file since we're using useEffect)
4. Look in the console and you should see the errors that look like the image below

**Expected behavior**
There should be no errors related to Rudderstack in the console.

**Screenshots**

![Image](https://github.com/user-attachments/assets/0ffb0c83-d3c1-41e4-8f1c-5ceda126d383)

**Additional Information (please complete the following information):**

- SDK installation type: NPM
- SDK version: 3.14.0
- Node version: v22.12.0
- NPM version: N/A (using `bun` )
- TypeScript version: v5.7.1
- Webpage URL: N/A
- Share the event payload: (if applicable)
- Integration that has the issue: (if applicable)
- Framework and version(e.g: Next.js, React, Vue): Next.js v 15.1.17
- Bundling toolset (e.g: Webpack, Rollup): Webpack

**Desktop (please complete the following information):**

- OS: macOS Sequoia 15.3
- Browser: Arc Browser v1.82.0

**Additional context**
I was seeing this in a repo with a lot of extra libraries and content, so I created a brand new project to see if I could reproduce, and I could. To confirm it wasn't just an issue with the `bun` runtime, I ran the new project with `npm`, `pnpm` and `bun` and all 3 exhibited the same issue.

**Comment by saikumarrs** [comment]
@riceboyler thanks for bringing it to our attention.
We'll investigate and get back to you at the earliest.

**Comment by riceboyler** [comment]
Just more info: reverting to v3.13.0 eliminates that error, so it appears to be something related to the changes in v3.14.0.

**Comment by saikumarrs** [comment]
Hello @riceboyler 
I'm unable to reproduce the error locally in Next.js apps. Maybe it is occurring only when a bundler like Webpack is used.

We've recently made a change to listen to all error events on the DOM. I believe that code gets executed on importing the package itself, causing the error.

Can you please confirm if you are able to reproduce the issue with one of our Next.js sample apps?
https://github.com/rudderlabs/rudder-sdk-js/tree/develop/examples/nextjs

**Comment by valp0** [comment]
Hello!
Just wanted to inform I was having the same problem. This problem appeared when I bumped the version of `@rudderstack/analytics-js` from `3.5.2` to `3.15.0`.
Just tried with version `3.13.0` and the problem seems to indeed go away.
I had this problem in a [Docusaurus](https://docusaurus.io/) project, so like previously mentioned this might be related to bundler usage.

**Comment by saikumarrs** [comment]
Hi @valp0,

Thanks for reaching out!

We've identified the root cause of the issue. It appears that @riceboyler instrumented the SDK inside layout.tsx (a server-side component) instead of page.tsx in the Next.js project, which is leading to unexpected behavior.

Additionally, we've discovered a bug in the SDK where global error event listeners are being registered upon importing the package, which is not ideal. We'll be addressing this in an upcoming release.

Stay tuned for updates, and let us know if you have any further questions!

**Comment by mgryszko** [comment]
I also stumbled upon the same issue. We evaluated RudderStack with 3.7.9 @rudderstack/analytics-js version. Now, after switching to 3.15.2 version, I started getting the same error in an Next.js application.

Although I'm initializing RudderStack on the client side in a React context provider, the problem lies in the server-side import evaluation (`import { RudderAnalytics } from "@rudderstack/analytics-js/bundled"`).

Here you have a sketch of the context provider code:

```ts
import { useIsClient } from "@uidotdev/usehooks";
import { RudderAnalytics } from "@rudderstack/analytics-js/bundled";

const isClient = useIsClient();

if (isClient) {
    const rudderAnalytics = new RudderAnalytics();
    rudderAnalytics.load(rudderConfig.writeKey, rudderConfig.dataPlaneUrl);
}
```

**Comment by riceboyler** [comment]
As an update, I'm seeing the same issues on 3.15.2 IN PAGES ROUTER, NOT the new App Router repo. So this appears to be impacting not only App Router/RSCs but now Pages Router as well with out React Server Components.

**Comment by saikumarrs** [comment]
Hello @mgryszko @riceboyler @valp0 
We've released a new version v3.16.0 with the issue addressed.

Could you please try and let us know if you are unblocked?

**Comment by mgryszko** [comment]
@saikumarrs I can confirm that the issue is gone in 3.16.1: I'm able to import `RudderAnalytics` on the server-side and initialize it on the client side. BTW, 3.16.0 was still buggy with respect to the import.
